#!/bin/bash
set -e

case "$1" in
  configure)
    echo "Please run /opt/mlnx-driver/install.sh to install MLNX_OFED DEBs..."

    # dpkg -i --force-confmiss '/opt/mlnx-driver/DEBS/ofed-scripts_24.10.OFED.24.10.2.1.8-1_amd64.deb' || true
    # dpkg -i --force-confmiss '/opt/mlnx-driver/DEBS/mlnx-tools_24.10-0.2410068_amd64.deb' || true
    # dpkg -i --force-confnew --force-confmiss '/opt/mlnx-driver/DEBS/mlnx-ofed-kernel-utils_24.10.OFED.24.10.2.1.8.1-1.kver.6.12.15-production+truenas_amd64.deb' || true
    # dpkg -i --force-confnew --force-confmiss '/opt/mlnx-driver/DEBS/mlnx-ofed-kernel-modules_24.10.OFED.24.10.2.1.8.1-1.kver.6.12.15-production+truenas_amd64.deb' || true
    # dpkg -i --force-confmiss '/opt/mlnx-driver/DEBS/iser-modules_24.10.OFED.24.10.2.1.8.1-1.kver.6.12.15-production+truenas_amd64.deb' || true
    # dpkg -i --force-confmiss '/opt/mlnx-driver/DEBS/isert-modules_24.10.OFED.24.10.2.1.8.1-1.kver.6.12.15-production+truenas_amd64.deb' || true
    # dpkg -i --force-confmiss '/opt/mlnx-driver/DEBS/srp-modules_24.10.OFED.24.10.2.1.8.1-1.kver.6.12.15-production+truenas_amd64.deb' || true
    # dpkg -i --force-confmiss '/opt/mlnx-driver/DEBS/mlnx-nvme-modules_24.10.OFED.24.10.2.1.8.1-1.kver.6.12.15-production+truenas_amd64.deb' || true
    # dpkg -i --force-confmiss '/opt/mlnx-driver/DEBS/fwctl-modules_24.10.OFED.24.10.2.1.8.1-1.kver.6.12.15-production+truenas_amd64.deb' || true
    # dpkg -i --force-confmiss '/opt/mlnx-driver/DEBS/rdma-core_2410mlnx54-1.2410068_amd64.deb' || true
    # dpkg -i --force-confmiss '/opt/mlnx-driver/DEBS/libibverbs1_2410mlnx54-1.2410068_amd64.deb' || true
    # dpkg -i --force-confmiss '/opt/mlnx-driver/DEBS/ibverbs-utils_2410mlnx54-1.2410068_amd64.deb' || true
    # dpkg -i --force-confmiss '/opt/mlnx-driver/DEBS/ibverbs-providers_2410mlnx54-1.2410068_amd64.deb' || true
    # dpkg -i --force-confmiss '/opt/mlnx-driver/DEBS/libibverbs-dev_2410mlnx54-1.2410068_amd64.deb' || true
    # dpkg -i --force-confmiss '/opt/mlnx-driver/DEBS/libibverbs1-dbg_2410mlnx54-1.2410068_amd64.deb' || true
    # dpkg -i --force-confmiss '/opt/mlnx-driver/DEBS/libibumad3_2410mlnx54-1.2410068_amd64.deb' || true
    # dpkg -i --force-confmiss '/opt/mlnx-driver/DEBS/libibumad-dev_2410mlnx54-1.2410068_amd64.deb' || true
    # dpkg -i --force-confmiss '/opt/mlnx-driver/DEBS/ibacm_2410mlnx54-1.2410068_amd64.deb' || true
    # dpkg -i --force-confmiss '/opt/mlnx-driver/DEBS/librdmacm1_2410mlnx54-1.2410068_amd64.deb' || true
    # dpkg -i --force-confmiss '/opt/mlnx-driver/DEBS/rdmacm-utils_2410mlnx54-1.2410068_amd64.deb' || true
    # dpkg -i --force-confmiss '/opt/mlnx-driver/DEBS/librdmacm-dev_2410mlnx54-1.2410068_amd64.deb' || true
    # dpkg -i --force-confmiss '/opt/mlnx-driver/DEBS/libibmad5_2410mlnx54-1.2410068_amd64.deb' || true
    # dpkg -i --force-confmiss '/opt/mlnx-driver/DEBS/libibmad-dev_2410mlnx54-1.2410068_amd64.deb' || true
    # dpkg -i --force-confmiss '/opt/mlnx-driver/DEBS/libibnetdisc5_2410mlnx54-1.2410068_amd64.deb' || true
    # dpkg -i --force-confmiss '/opt/mlnx-driver/DEBS/infiniband-diags_2410mlnx54-1.2410068_amd64.deb' || true
    # dpkg -i --force-confmiss '/opt/mlnx-driver/DEBS/kernel-mft-modules_4.30.1.113-1.kver.6.12.15-production+truenas_all.deb' || true
    # dpkg -i --force-confmiss '/opt/mlnx-driver/DEBS/srptools_2410mlnx54-1.2410068_amd64.deb' || true
    # dpkg -i --force-confmiss '/opt/mlnx-driver/DEBS/rshim_2.1.10-0.g4f69018.2410218_amd64.deb' || true
    # dpkg -i --force-confmiss '/opt/mlnx-driver/DEBS/mlnx-ethtool_6.9-1.2410068_amd64.deb' || true
    # dpkg -i --force-confmiss '/opt/mlnx-driver/DEBS/mlnx-iproute2_6.10.0-1.2410218_amd64.deb' || true
    # dpkg -i --force-confmiss '/opt/mlnx-driver/DEBS/perftest_24.10.0-0.65.g9093bae.2410068_amd64.deb' || true
    # dpkg -i --force-confmiss '/opt/mlnx-driver/DEBS/ibsim_0.12-1.2410068_amd64.deb' || true
    # dpkg -i --force-confmiss '/opt/mlnx-driver/DEBS/ibsim-doc_0.12-1.2410068_all.deb' || true
    # dpkg -i --force-confmiss '/opt/mlnx-driver/DEBS/sockperf_3.10-0.git5ebd327da983.2410068_amd64.deb' || true
    # dpkg -i --force-confmiss '/opt/mlnx-driver/DEBS/ucx_1.18.0-1.2410068_amd64.deb' || true
    # dpkg -i --force-confmiss '/opt/mlnx-driver/DEBS/knem-modules_1.1.4.90mlnx3-OFED.23.10.0.2.1.1.kver.6.12.15-production+truenas_amd64.deb' || true
    # dpkg -i --force-confmiss '/opt/mlnx-driver/DEBS/libxpmem0_2.7-0.2310055_amd64.deb' || true
    # dpkg -i --force-confmiss '/opt/mlnx-driver/DEBS/libxpmem-dev_2.7-0.2310055_amd64.deb' || true
    # dpkg -i --force-confmiss '/opt/mlnx-driver/DEBS/mlnx-nfsrdma-modules_24.10.OFED.24.10.2.1.8.1-1.kver.6.12.15-production+truenas_amd64.deb' || true
    #
    # # Optionally fix any broken dependencies
    # apt-get install -f -y

    ;;
esac

exit 0
